### ISSUE TITLE
jazz packages not available on Observable

### ISSUE THREAD

**Issue by devgru** [garden-co/classic-jazz#202]
Trying to probe `jazz-react` or `jazz-browser` fails on Observable platform.

I've checked using Tom MacWright's [module debugger](https://observablehq.com/@observablehq/module-require-debugger).

I've tried to replicate the problem locally using `packd` and from the logs it looks like the problem might be in crypto libraries.

```
'node:crypto' is imported by .tmp/72c7fdc7693293db071a588091d794e76d42546b/package/node_modules/cojson/dist/crypto/WasmCrypto.js, but could not be resolved – treating it as an external dependency
'@scure/bip39' is imported by .tmp/72c7fdc7693293db071a588091d794e76d42546b/package/dist/auth/PassphraseAuth.js, but could not be resolved – treating it as an external dependency
packd error [jazz-browser] Unexpected token Error: Unexpected token
    at error (/Users/devgru/Peers/LocalFirst/packd/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/Users/devgru/Peers/LocalFirst/packd/node_modules/rollup/dist/shared/node-entry.js:9824:16)
    at tryParse (/Users/devgru/Peers/LocalFirst/packd/node_modules/rollup/dist/shared/node-entry.js:9717:23)
    at Module.setSource (/Users/devgru/Peers/LocalFirst/packd/node_modules/rollup/dist/shared/node-entry.js:10080:33)
    at /Users/devgru/Peers/LocalFirst/packd/node_modules/rollup/dist/shared/node-entry.js:12366:20
    at async Promise.all (index 19)
    at async Promise.all (index 0)
    at async Promise.all (index 3)
    at async Promise.all (index 0)
    at async Promise.all (index 0)

```

**Comment by devgru** [comment]
Actually, looking inside `packd` error reveals that the problem is in completely different place, one of the files in `effect` package:

`.../packd/.tmp/72c7fdc7693293db071a588091d794e76d42546b/package/node_modules/effect/dist/esm/Data.js`

<img width="422" alt="Screenshot 2024-05-31 at 15 31 05" src="https://github.com/gardencmp/jazz/assets/63065/0c5ceb18-fd53-493e-9ada-bc90c615595d">

That makes me wonder whether `effect` is rollup-compatible or the problem is somewhere deeper.

**Comment by bensleveritt** [comment]
👋 @devgru Thanks for raising this. We've had a lot of changes in the past 4 months, and at least one instance of your Observable debugger seems to work (SkyPack). Would you like to try again?

**Comment by devgru** [comment]
@bensleveritt thanks for the update! I'd be happy to try once again, but not sure when I'll find time to do that :-)

**Comment by bensleveritt** [comment]
No worries, if you do, let us know if you have any issues. I'll close for now

> [@bensleveritt](https://github.com/bensleveritt) thanks for the update! I'd be happy to try once again, but not sure when I'll find time to do that :-)
