### ISSUE TITLE
Internal error: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Aslam97** [garden-co/classic-jazz#280]
### Installed:

```bash
"next": "14.2.5",
"jazz-react": "^0.7.25",
"jazz-tools": "^0.7.25",
```

### Nextconfig

```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false
}

export default nextConfig
```

### Provider

```ts
"use client"

import { createJazzReactContext, PasskeyAuth } from "jazz-react"
import { AuthUI } from "@/components/custom/auth-ui"
import { LaAccount } from "../schema"

const appName = process.env.NEXT_PUBLIC_APP_NAME!

const auth = PasskeyAuth<LaAccount>({
	appName,
	Component: AuthUI,
	accountSchema: LaAccount
})

const Jazz = createJazzReactContext({
	auth,
	peer: "wss://mesh.jazz.tools/?key=email@gmail.com"
})

export const { useAccount, useCoState } = Jazz

export function JazzProvider({ children }: { children: React.ReactNode }) {
	return <Jazz.Provider>{children}</Jazz.Provider>
}
```

### Error

```bash
GET /_next/static/chunks/app/(pages)/pages/%5Bid%5D/index.js.map 404 in 468ms
 GET /favicon.ico 200 in 33ms
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 ✓ Compiled in 3.7s (6249 modules)
 ⨯ Internal error: ReferenceError: window is not defined
    at new BrowserPasskeyAuth (./node_modules/.pnpm/jazz-browser@0.7.25/node_modules/jazz-browser/dist/auth/PasskeyAuth.js:13:19)
    at eval (./node_modules/.pnpm/jazz-react@0.7.25_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/jazz-react/dist/auth/PasskeyAuth.js:20:20)
    at Object.oN [as useMemo] (/Users/aslamh/Sites/learn-anything.xyz/web/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:12:68806)
    at t.useMemo (/Users/aslamh/Sites/learn-anything.xyz/web/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:162732)
    at useLocalAuth (./node_modules/.pnpm/jazz-react@0.7.25_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/jazz-react/dist/auth/PasskeyAuth.js:19:68)
    at Provider (./node_modules/.pnpm/jazz-react@0.7.25_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/jazz-react/dist/index.js:28:42)
    at au (/Users/aslamh/Sites/learn-anything.xyz/web/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /Users/aslamh/Sites/learn-anything.xyz/web/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/Users/aslamh/Sites/learn-anything.xyz/web/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
```

**Comment by aeplay** [comment]
Thanks for reporting!

**Comment by gdorsi** [comment]
Should be fixed with Jazz 0.10.0
